project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"

website:
  twitter-card: true
  search: false
  back-to-top-navigation: true
  favicon: "assets/favicons/favicon.ico" 
  page-footer:
    left: #add source code icon 
      - icon: code-slash
        href: https://github.com/lukmayer/website
        aria-label: Source code
    center: |
      Powered by <a href='https://quarto.org' target='_blank'>Quarto</a>
    right:
      - icon: rss
        href: /blog/index.xml
        aria-label: Blog RSS feed
  open-graph: true
  site-url: "https://lukmayer.github.io"
  title: "Lukas W. Mayer"
  navbar:
    logo: "assets/favicons/android-chrome-512x512.png"
    left:
      - href: index.qmd
        text: "Home"
      - href: research/index.qmd
        text: "Research"
      - href: cv/index.qmd
        text: "CV"
      - href: blog/index.qmd
        text: "Blog"
      - href: about/index.qmd
        text: "About"
    right:
      - text: "Login"
        href: https://lukmayer.github.io/login_portal/

blog:
  title: "Luke's Blog"

format:
  html:
    code-line-numbers: true
    smooth-scroll: true
    theme: [darkly, theme-dark.scss]
    css: styles.css
    toc: true
    footnotes-hover: true
    reference-location: margin
    link-external-newwindow: true
    link-external-filter: "https://www.lukmayer.github.io"
    canonical-url: true
    toc-location: left
    toc-title: "Sections:"
    toc-depth: 4
    toc-expand: 2
    title-block-style: manuscript
    title-block-banner: true
    title-block-banner-color: "#00bf63"
    title-block-categories: true
    code-fold: show
    code-copy: true
    code-tools: false
    code-overflow: scroll
    code-block-border-left: true
    highlight-style: atom-one
    fig-responsive: true
    lightbox: true
    include-after-body: page-transitions.html

    
execute:
  cache: true
  freeze: auto

extensions:
  - animate
  
  
  